remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Analysis of Top Hits Spotify from 2000-2019
description: [This is our final project for Business Application programming]